Ros2 devel
ros/filters pull request #24
Opened 2018-12-24 11:36 UTC by swatifulzele

Migrated header and source files, CMakeLists.txt, package.xml, test.cpp, default_plugins.xml, launch and yaml files referring the ROS1 lunar-devel branch filters package folder. The package builds successfully and all **28 tests** cases passing on **bouncy**.
Note: There is change in the syntax of yaml files.

2019-02-05 12:57 UTC, swatifulzele commented
@tfoote 
I have migrated the filters package and the related design changes has been well explained in the README.cmd file. The latest commit shows the changes for the yaml file support in generic way as mentioned in the README.cmd file. All test cases are passing and it has been used with the ros2 ported laser_assembler package and builds successfully. Please review and give suggestions if any.

2020-04-04 01:06 UTC, sloretz requested changes
Thanks for the PR. I left a few comments below, and since it's been a long time I opened an alternative PR #32 in case you weren't interested in this anymore.

2020-04-04 01:06 UTC, sloretz commented on LICENSE
> +                        http://www.apache.org/licenses/
If I understand correctly, I think the license has to stay BSD since it's a port of [code already under aBSD license](https://github.com/ros/filters/blob/67768ed321df2a0af3e0b4edd046bd29633202b9/package.xml#L11). Please keep the license the same.

2020-04-04 01:06 UTC, sloretz commented on CONTRIBUTING.md
> +[license](http://www.apache.org/licenses/LICENSE-2.0.html):
Same comment that this package needs to stay BSD licensed

2020-04-04 01:06 UTC, sloretz commented on CMakeLists.txt
> +  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
Please use [`CMAKE_CXX_STANDARD`](https://github.com/ros2/rclcpp/blob/3ec882cd2db97d84330197bb946bd31572215489/rclcpp/CMakeLists.txt#L20-L22) or [`CXX_STANDARD`](https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html) instead so CMake can pick the right compiler flags on each platform.

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_base.h
> -/*
I recommend not changing the file names, or if you do, do the rename it in a separate commit with no other changes. As it is the history is lost when looking at `filter_base.hpp`. This is why the PR doesn't show the diff for this file.

2020-04-04 01:06 UTC, sloretz commented on CMakeLists.txt
> +include_directories(${INCLUDE_DIRS})
Use [`ament_target_dependencies()`](https://github.com/ament/ament_cmake/blob/c66c6a0607f878788fd5ac8fd17151222c4238c0/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake#L16-L33) instead of `include_directories()` and `link_directories()` so this will continue to work when ament_cmake switches to interface targets instead of CMake variables.

2020-04-04 01:06 UTC, sloretz commented on CMakeLists.txt
>  install(FILES default_plugins.xml
[`pluginlib_export_plugin_description_file()`](https://github.com/ros/pluginlib/blob/37e1763edb988e3c4e07de76a4e22163a81b5219/pluginlib/cmake/pluginlib_export_plugin_description_file.cmake#L23-L81) installs this file to the correct spot, no need for this `install()`

2020-04-04 01:06 UTC, sloretz commented on CMakeLists.txt
> +ament_export_include_directories(${INCLUDE_DIRS})
This should only be `ament_export_include_directories(include)`. Headers for dependencies are exported by [`ament_export_dependencies()`](https://github.com/ament/ament_cmake/blob/c66c6a0607f878788fd5ac8fd17151222c4238c0/ament_cmake_export_dependencies/cmake/ament_export_dependencies.cmake#L16-L25)

2020-04-04 01:06 UTC, sloretz commented on CMakeLists.txt
> +    find_package(ament_cmake_gtest REQUIRED)
if `ament_cmake_gtest` is a `<test_depend>` in the `package.xml`, then `ament_lint_auto_find_test_dependencies()` below will find this package.

2020-04-04 01:06 UTC, sloretz commented on CMakeLists.txt
> +        DESTINATION lib/${PROJECT_NAME})
Don't install test targets

2020-04-04 01:06 UTC, sloretz commented on CMakeLists.txt
>  find_package(Boost COMPONENTS system filesystem thread REQUIRED)
Can we get rid of the dependency on `boost`?

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_base.hpp
> +  bool configure(rclcpp::Node::SharedPtr node)
Hmm this excludes lifecycle nodes. I think it should use the node interfaces instead:

```C++
    const rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr & node_logger,
    const rclcpp::node_interfaces::NodeParametersInterface::SharedPtr & node_params
```

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_base.hpp
> +      RCLCPP_DEBUG(node->get_logger(), "Filter type already being reconfigured ");
This was a warning before

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_base.hpp
> +    parameters_and_prefixes = node_->list_parameters({}, 10);
I think this should declare parameters first. Given the prefix (`filterN` in a chain, etc) Base could declare the `name` and `type` parameters. It would be up to the subclass to declare the parameters under `params`

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_base.hpp
> +template<typename T>
Please add back the whitespace between the two classes

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_base.hpp
> +    rclcpp::Node::SharedPtr node)
same comment about using only the necessary node interfaces instead of the node itself.

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_base.hpp
> +      RCLCPP_DEBUG(node->get_logger(), "Filter type already being reconfigured ");
This was a warning before

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_chain.hpp
> +#include "boost/shared_ptr.hpp"
Remove unused boost headers

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_base.hpp
> +#include <boost/scoped_ptr.hpp>
Remove unused boost headers

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_chain.hpp
> +    for (unsigned int i = 0; i < libs.size(); i++) {
use `size_t` to compare against `libs.size()`, also `++i` instead of `i++`

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_chain.hpp
> +      lib_string = lib_string + std::string(", ") + libs[i];
`lib_string` appears to be unused

2020-04-04 01:06 UTC, sloretz commented on include/filters/filter_chain.hpp
> +          for (int i = 0; i < static_cast<int>(filter_name.length()); i++) {
use `size_t` instead of casting the length to an integer

2020-04-04 01:06 UTC, sloretz commented on launch/test_chain.launch.py
> +#!/usr/bin/python3.6
no need for a `shebang` since the file isn't executed directly

2020-04-04 01:06 UTC, sloretz commented on launch/test_median.launch.py
> +#!/usr/bin/python3.6
same comment about shebang

2020-04-07 16:03 UTC, sloretz commented
Thanks for the PR! This work is being continued in #32, so I'll close this one.

2020-04-07 16:03 UTC, closed without merging