[Windows][lunar] Fix run_tests build breaks on Windows\MSVC
ros/filters pull request #26
Opened 2019-04-03 07:28 UTC by seanyen

On Windows, there is no native `gettimeofday()` API so instead use `GetTickCount` to make the seed for random number generation.

2019-06-27 03:24 UTC, seanyen commented
@tfoote Hope I am pinging the correct owner. I'd love to get some feedback to move it forward.

2020-01-14 09:35 UTC, seanyen commented
@tfoote Happy new year. This is ready for review and merge. Hope we could move this forward on the upstream for `noetic` and `melodic`.

2020-02-07 00:34 UTC, tfoote requested changes
It looks like we might be able to simplify this just a little bit, otherwise it looks good to me.

2020-02-07 00:34 UTC, tfoote commented on test/test_params.cpp
> +#ifndef _WIN32
Is this include unnecessary and we can remove it instead of adding the ifndef?

2020-02-07 00:34 UTC, tfoote commented on test/test_transfer_function.cpp
> +#ifndef _WIN32
Is this include unnecessary and we can remove it instead of adding the ifndef?

2020-02-07 01:53 UTC, seanyen commented
@tfoote Thanks for the feedback! On a second revisit this change, I attempted to use C standard library instead. That way makes the code more portable.

Now waiting for the CI result..

2020-02-07 04:13 UTC, seanyen commented
@tfoote `Npr__filters__ubuntu_focal_amd64` failed at rosdep. I think it is safe to ignore?

2020-02-07 06:29 UTC, tfoote approved these changes
Thanks this looks much cleaner now.

Yes, we can ignore the Noetic builds, we're still in the bootstrap phase and they won't work until all of the necessary dependencies have been released.

2020-02-07 06:30 UTC, merged